[package]
name = "esports-ranker"
version = "0.1.0"
edition = "2021"

[dependencies]
csv = "1.3.0"
reqwest = { version = "0.12.9", features = ["blocking", "json"] }
scraper = "0.21.0"
serde = { version = "1.0.214", features = ["derive"]}
tokio = { version = "1.41.1", features = ["full"] }
